spring:
  profiles:
    active: local
    include: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
#    defer-datasource-initialization: true
  datasource:
    url: jdbc:mariadb://svc.sel4.cloudtype.app:31805/reservation
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
#    h2 설정
#    url: jdbc:h2:mem:testreservation
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  data:
    redis:
      host: svc.sel3.cloudtype.app
      port: 31076

  servlet.multipart.max-file-size: 20MB
  servlet.multipart.max-request-size: 25MB

jwt:
  issuer: narvis2@naver.com
  secret_key: study-springboot
  refresh_secret_key: refresh-study-springboot
  expire_time: 7200 # 60 * 60 * 2 (2시간)
  refresh_expire_time: 604800 # 60 * 60 * 24 * 7 (7일)