spring:
  profiles:
    active: local
    include: secret
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testreservation
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB

jwt:
  issuer: narvis2@naver.com
  secret_key: study-springboot
  refresh_secret_key: refresh-study-springboot
  expire_time: 7200 # 60 * 60 * 2 (2시간)
  refresh_expire_time: 604800 # 60 * 60 * 24 * 7 (7일)