naver_sens:
  url:
    base: https://sens.apigw.ntruss.com
    end_point: /sms/v2/services/
  key:
    access: 983r0KMkSffl1u3knRI2
    secret: 9uy9tik0VLkUrTGE58nEfphjmc15Ifrnx8SR5Ovx
  id:
    service: ncp:sms:kr:266976528021:reservation-api-server