INSERT INTO seat (seat_type) VALUES ('A_1')
INSERT INTO seat (seat_type) VALUES ('A_2')
INSERT INTO seat (seat_type) VALUES ('A_3')
INSERT INTO seat (seat_type) VALUES ('A_4')
INSERT INTO seat (seat_type) VALUES ('A_5')
INSERT INTO seat (seat_type) VALUES ('A_6')
INSERT INTO seat (seat_type) VALUES ('A_7')
INSERT INTO seat (seat_type) VALUES ('A_8')
INSERT INTO seat (seat_type) VALUES ('B')
INSERT INTO seat (seat_type) VALUES ('C')

INSERT INTO role (role_type) VALUES ('ROLE_ALLOW')
INSERT INTO role (role_type) VALUES ('ROLE_NOT_ALLOW')
INSERT INTO role (role_type) VALUES ('ROLE_STOP')
INSERT INTO role (role_type) VALUES ('ROLE_SLEEPER')
INSERT INTO role (role_type) VALUES ('ROLE_ADMIN')
INSERT INTO role (role_type) VALUES ('ROLE_MASTER')